apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::470421654936:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::470421654936:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-SDT820QA50J
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-19T06:44:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1445"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7f9a3071-e262-4173-80a6-12da4afb6c68
